import {
  GiBroadsword,
  GiBread,
  GiCape,
  GiCrownedHeart,
  GiCrown,
  GiGems,
  GiHeartNecklace,
  GiKey,
  GiOpenBook,
  GiPlainDagger,
  GiPocketBow,
  GiPotionBall,
  GiShield,
  GiSpellBook,
  GiTorch,
  GiTreasureMap,
  GiTwoCoins,
  GiWingedEmblem,
  GiWingedScepter,
} from "react-icons/gi";

export const atmosphereColors = {
  dark: { bg: "#0a0608", accent: "#8b1a1a", glow: "rgba(139,26,26,0.3)" },
  mystic: { bg: "#060a14", accent: "#4a1a8b", glow: "rgba(74,26,139,0.3)" },
  battle: { bg: "#140806", accent: "#8b3a1a", glow: "rgba(139,58,26,0.4)" },
  calm: { bg: "#060e0a", accent: "#1a6b3a", glow: "rgba(26,107,58,0.3)" },
  danger: { bg: "#140405", accent: "#b01a1a", glow: "rgba(176,26,26,0.5)" },
};

export const ITEM_ICONS = {
  "daga,cuchillo": GiPlainDagger,
  "capa,ropa": GiCape,
  "pan,cantimplora": GiBread,
  "pocion,poción": GiPotionBall,
  llave: GiKey,
  mapa: GiTreasureMap,
  "grimorio,tomo": GiSpellBook,
  libro: GiOpenBook,
  "oro,moneda": GiTwoCoins,
  escudo: GiShield,
  arco: GiPocketBow,
  "amuleto,collar": GiHeartNecklace,
  antorcha: GiTorch,
  "marca,guardian,guardián": GiWingedEmblem,
  "gema,cristal": GiGems,
  "bendicion,bendición": GiCrownedHeart,
  corona: GiCrown,
  cetro: GiWingedScepter,
  default: GiBroadsword,
};
